baseURL = 'https://alexrokotin.github.io/staticsite/'
languageCode = 'ru'
title = 'Зарядись матиууаацией!'
theme = "ananke"

[params]
  headerTitle = "Welcome to My Static Site"
  description = "A simple Hugo site with Ananke theme"
